from config.settings.apps import *
from config.settings.base import *
from config.settings.db import *
from config.settings.files import *
from config.settings.firebase import *
from config.settings.handler import *
from config.settings.redis import *
from config.settings.rest_framework import *
from config.settings.swagger import *
